import sqlite3
conn = sqlite3.connect('D:/test/EngramNote/backend/data/db/engramnote.db')
c = conn.cursor()
c.execute("SELECT COUNT(*) FROM knowledge_cards WHERE note_id='93b47cff-6f38-4b83-a6f3-ab6d34fcc140'")
print(f'Cards for new note: {c.fetchone()[0]}')
c.execute("SELECT COUNT(*) FROM knowledge_cards")
print(f'Total cards: {c.fetchone()[0]}')
c.execute("SELECT COUNT(*) FROM quiz_items")
print(f'Total quiz items: {c.fetchone()[0]}')
conn.close()
