"""add note_material_links and note_annotations tables, add link_signature and is_stale to assessment_results

Revision ID: 002_add_link_annotation
Revises: 001_add_note_role
Create Date: 2026-07-02

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_add_link_annotation'
down_revision: Union[str, None] = '001_add_note_role'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建笔记-资料关联表
    op.create_table(
        'note_material_links',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('personal_note_id', sa.String(), nullable=False),
        sa.Column('material_note_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['personal_note_id'], ['notes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['material_note_id'], ['notes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('personal_note_id', 'material_note_id', name='uq_note_material_link'),
    )
    op.create_index('ix_note_material_links_user_id', 'note_material_links', ['user_id'], unique=False)
    op.create_index('ix_note_material_links_personal_note_id', 'note_material_links', ['personal_note_id'], unique=False)
    op.create_index('ix_note_material_links_material_note_id', 'note_material_links', ['material_note_id'], unique=False)

    # 创建笔记标注表
    op.create_table(
        'note_annotations',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('note_id', sa.String(), nullable=False),
        sa.Column('view_mode', sa.String(length=20), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('text_content', sa.Text(), nullable=False),
        sa.Column('context_before', sa.Text(), nullable=False, server_default=''),
        sa.Column('context_after', sa.Text(), nullable=False, server_default=''),
        sa.Column('color', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_note_annotations_user_id', 'note_annotations', ['user_id'], unique=False)
    op.create_index('ix_note_annotations_note_id', 'note_annotations', ['note_id'], unique=False)

    # 为 assessment_results 表新增 link_signature 与 is_stale 列
    op.add_column('assessment_results', sa.Column('link_signature', sa.String(length=64), nullable=True))
    op.add_column('assessment_results', sa.Column('is_stale', sa.Boolean(), server_default='0', nullable=False))
    op.create_index('ix_assessment_results_link_signature', 'assessment_results', ['link_signature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assessment_results_link_signature', table_name='assessment_results')
    op.drop_column('assessment_results', 'is_stale')
    op.drop_column('assessment_results', 'link_signature')

    op.drop_index('ix_note_annotations_note_id', table_name='note_annotations')
    op.drop_index('ix_note_annotations_user_id', table_name='note_annotations')
    op.drop_table('note_annotations')

    op.drop_index('ix_note_material_links_material_note_id', table_name='note_material_links')
    op.drop_index('ix_note_material_links_personal_note_id', table_name='note_material_links')
    op.drop_index('ix_note_material_links_user_id', table_name='note_material_links')
    op.drop_table('note_material_links')
    # ### end Alembic commands ###
