"""add card_category / is_key_point / is_difficulty / mastery_level / source_note_ids / parent_card_id to knowledge_cards

Revision ID: 003_knowledge_card_category_mastery
Revises: 002_add_link_annotation
Create Date: 2026-07-07

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003_knowledge_card_category_mastery'
down_revision: Union[str, None] = '002_add_link_annotation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 为 knowledge_cards 表新增卡片分类、标记、掌握度、来源笔记、父卡片等列
    op.add_column('knowledge_cards', sa.Column('card_category', sa.Enum('regular', 'blind_spot', 'extension', name='cardcategory'), server_default='regular', nullable=False))
    op.add_column('knowledge_cards', sa.Column('is_key_point', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('knowledge_cards', sa.Column('is_difficulty', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('knowledge_cards', sa.Column('mastery_level', sa.Float(), server_default='0', nullable=False))
    op.add_column('knowledge_cards', sa.Column('source_note_ids', sa.JSON(), nullable=True))
    op.add_column('knowledge_cards', sa.Column('parent_card_id', sa.String(), nullable=True))
    op.create_index('ix_knowledge_cards_parent_card_id', 'knowledge_cards', ['parent_card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_cards_parent_card_id', table_name='knowledge_cards')
    op.drop_column('knowledge_cards', 'parent_card_id')
    op.drop_column('knowledge_cards', 'source_note_ids')
    op.drop_column('knowledge_cards', 'mastery_level')
    op.drop_column('knowledge_cards', 'is_difficulty')
    op.drop_column('knowledge_cards', 'is_key_point')
    op.drop_column('knowledge_cards', 'card_category')
    # ### end Alembic commands ###
