"""add note_versions, learning_goals, daily_plans tables

Revision ID: 004_v2_models
Revises: 003_knowledge_card_category_mastery
Create Date: 2026-07-18

本迁移新增三张表用于支持版本历史与学习目标功能：
- note_versions: 笔记 Markdown 内容的版本历史快照
- learning_goals: 用户设定的学习目标
- daily_plans: 基于活跃目标生成的每日任务推荐计划
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004_v2_models'
down_revision: Union[str, None] = '003_knowledge_card_category_mastery'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建笔记版本历史表
    op.create_table(
        'note_versions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('note_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(length=20), nullable=False),
        sa.Column('content_size', sa.Integer(), nullable=False),
        sa.Column('change_summary', sa.Text(), nullable=True),
        sa.Column('storage_path', sa.String(length=1000), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_note_versions_note_id', 'note_versions', ['note_id'], unique=False)
    op.create_index('ix_note_versions_user_id', 'note_versions', ['user_id'], unique=False)

    # 创建学习目标表
    op.create_table(
        'learning_goals',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False, server_default='weekly'),
        sa.Column('scope_notes', sa.JSON(), nullable=True),
        sa.Column('scope_folders', sa.JSON(), nullable=True),
        sa.Column('target_mastery', sa.Float(), nullable=False, server_default='80.0'),
        sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='active'),
        sa.Column('progress_cache', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('last_progress_refresh', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_learning_goals_user_id', 'learning_goals', ['user_id'], unique=False)
    op.create_index('ix_learning_goals_status', 'learning_goals', ['status'], unique=False)

    # 创建每日计划表
    op.create_table(
        'daily_plans',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('goal_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('plan_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('recommended_tasks', sa.JSON(), nullable=True),
        sa.Column('completed_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('total_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['goal_id'], ['learning_goals.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_daily_plans_user_id', 'daily_plans', ['user_id'], unique=False)
    op.create_index('ix_daily_plans_goal_id', 'daily_plans', ['goal_id'], unique=False)
    op.create_index('ix_daily_plans_plan_date', 'daily_plans', ['plan_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 按依赖顺序倒序删除：先删叶子表 daily_plans，再删 learning_goals，最后删 note_versions
    op.drop_index('ix_daily_plans_plan_date', table_name='daily_plans')
    op.drop_index('ix_daily_plans_goal_id', table_name='daily_plans')
    op.drop_index('ix_daily_plans_user_id', table_name='daily_plans')
    op.drop_table('daily_plans')

    op.drop_index('ix_learning_goals_status', table_name='learning_goals')
    op.drop_index('ix_learning_goals_user_id', table_name='learning_goals')
    op.drop_table('learning_goals')

    op.drop_index('ix_note_versions_user_id', table_name='note_versions')
    op.drop_index('ix_note_versions_note_id', table_name='note_versions')
    op.drop_table('note_versions')
    # ### end Alembic commands ###
