"""add projects table and notes.project_id

Revision ID: 005_add_projects
Revises: 004_v2_models
Create Date: 2026-08-10

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005_add_projects'
down_revision: Union[str, None] = '004_v2_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 项目表：项目隔离 + 状态旁载 Vault 结构的项目层
    op.create_table(
        'projects',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=60), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_slug', 'projects', ['slug'], unique=False)

    # 笔记表新增 project_id 列（可空，兼容未归入项目的旧数据）
    op.add_column('notes', sa.Column('project_id', sa.String(), nullable=True))
    op.create_index('ix_notes_project_id', 'notes', ['project_id'], unique=False)
    op.create_foreign_key('fk_notes_project_id_projects', 'notes', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notes_project_id_projects', 'notes', type_='foreignkey')
    op.drop_index('ix_notes_project_id', table_name='notes')
    op.drop_column('notes', 'project_id')
    op.drop_index('ix_projects_slug', table_name='projects')
    op.drop_index('ix_projects_user_id', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
